on:
  schedule:
  - cron: '0 */6 * * *'

jobs:
  RSS-to-Zulip:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: |-
        pip install \
         feedparser \
         git+https://github.com/zulip/python-zulip-api.git#subdirectory=zulip
        $HOME/.local/share/zulip/integrations/rss/rss-bot \
         --site '${{ secrets.zulip_organization_url }}' \
         --api-key '${{ secrets.zulip_bot_key }}' \
         --user '${{ secrets.zulip_bot_email }}' \
         --feed-file rss-feeds \
         --data-dir data/ \
         --stream RSS
        git config --global user.email "zulip-rss-bot@users.noreply.github.com"
        git config --global user.name "RSS Bot"
        git add --all
        git commit -m "Update hashes."
        git gc
        git remote add origin2 https://${GITHUB_ACTOR}:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}
        git push origin2 HEAD:main
